### ISSUE TITLE
depreciation

### ISSUE THREAD

**Issue by ipwnosx** [realKazehaya/LicenseSystem-Discord-Bot#1]
(node:23) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/container/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (/home/container/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/container/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/container/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/container/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (/home/container/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/container/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/container/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:49) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/container/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (/home/container/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/container/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/container/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
(node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:49) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fekanolleka** [comment]
Did you add the token before trying to start the bot?

**Comment by ipwnosx** [comment]
> Did you add the token before trying to start the bot?

you should respond to me via twitter, i already messaged you.
i have proposition
